openapi: 3.0.0
info:
  title: Course Management API
  description: API cho phép mentor quản lý khóa học
  version: 1.0.0

paths:
  /api/Courses:
    post:
      summary: Tạo khóa học mới
      description: Cho phép mentor tạo một khóa học mới
      tags:
        - Courses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - description
                - categoryId
                - status
                - level
                - duration
              properties:
                title:
                  type: string
                  description: Tiêu đề khóa học
                  maxLength: 100
                description:
                  type: string
                  description: Mô tả khóa học
                  maxLength: 1000
                categoryId:
                  type: string
                  format: uuid
                  description: ID của danh mục
                status:
                  type: string
                  enum: [Draft, Published, Archived]
                  description: Trạng thái khóa học
                level:
                  type: string
                  enum: [Beginner, Intermediate, Advanced]
                  description: Cấp độ khóa học
                duration:
                  type: string
                  description: Thời lượng khóa học
                  minLength: 6
                  maxLength: 100
                tags:
                  type: array
                  items:
                    type: string
                  description: Danh sách tags của khóa học
      responses:
        "201":
          description: Khóa học được tạo thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourseDetailsResponse"
        "400":
          description: Dữ liệu không hợp lệ
        "409":
          description: Xung đột dữ liệu
        "500":
          description: Lỗi server

  /api/Courses/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    put:
      summary: Cập nhật khóa học
      description: Cho phép mentor cập nhật thông tin khóa học
      tags:
        - Courses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - description
                - categoryId
                - status
                - level
                - duration
              properties:
                title:
                  type: string
                  description: Tiêu đề khóa học
                  maxLength: 100
                description:
                  type: string
                  description: Mô tả khóa học
                  maxLength: 1000
                categoryId:
                  type: string
                  format: uuid
                  description: ID của danh mục
                status:
                  type: string
                  enum: [Draft, Published, Archived]
                  description: Trạng thái khóa học
                level:
                  type: string
                  enum: [Beginner, Intermediate, Advanced]
                  description: Cấp độ khóa học
                duration:
                  type: string
                  description: Thời lượng khóa học
                  minLength: 6
                  maxLength: 100
                tags:
                  type: array
                  items:
                    type: string
                  description: Danh sách tags của khóa học
      responses:
        "204":
          description: Cập nhật thành công
        "400":
          description: Dữ liệu không hợp lệ
        "404":
          description: Không tìm thấy khóa học
        "409":
          description: Xung đột dữ liệu
        "500":
          description: Lỗi server

    delete:
      summary: Xóa khóa học
      description: Cho phép mentor xóa khóa học
      tags:
        - Courses
      responses:
        "204":
          description: Xóa thành công
        "404":
          description: Không tìm thấy khóa học
        "500":
          description: Lỗi server

components:
  schemas:
    CourseDetailsResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        categoryName:
          type: string
        status:
          type: string
          enum: [Draft, Published, Archived]
        level:
          type: string
          enum: [Beginner, Intermediate, Advanced]
        duration:
          type: string
        created:
          type: string
          format: date-time
        lastUpdated:
          type: string
          format: date-time
        tags:
          type: array
          items:
            type: string

security:
  - BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: Courses
    description: Quản lý khóa học
