export const pathName = {
  home: "/",
  category: "/category",
  adminCourse: "/admin/course",
  mentorCourse: "/mentor/course",
  register: "/register",
  login: "/login",
  approval: "/approval",
  resetPassword: "/reset-password",
  forgotPassword: "/forgot-passord",
  oauthcallback: "/oauth-callback",
  userList: "/users-listing",
  mentorStatus: "/status",
  unauthorized: "/unauthorized",
  profile: "/profile",
  bookingSession: "/booking-session/:id",
  mentorDashboard: "/mentor-dashboard",
  sessionManagement: "/session-management/:id",
  mentorProfile: "/mentor-profile/:id",
  editProfile: "/edit-profile",
  mentorAvailability: "/mentor/availability",
  findmentor: "/find-mentor",
  leanerSessionManagement : "/learner/session-management",
};
