export const pathName = {
  home: "/",
  category: "/category",
  course: "/course",
  register: "/register",
  login: "/login",
  approval: "/approval",
  resetPassword: "/reset-password",
  forgotPassword: "/forgot-passord",
  oauthcallback: "/oauth-callback",
  userList: "/users-listing",
  mentorStatus: "/status",
  unauthorized: "/unauthorized",
  bookingSession: "/booking-session",
  mentorDashboard: "/mentor-dashboard",
  sessionManagement: "/session-management",
  mentorProfile: "/mentor-profile",
};
