// <auto-generated />
using System;
using Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515084123_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CourseCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CourseCount = 0,
                            Description = "Courses related to software development and programming languages.",
                            Name = "Programming",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CourseCount = 0,
                            Description = "Frontend and backend development tutorials and courses.",
                            Name = "Web Development",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CourseCount = 0,
                            Description = "Learn data analysis, visualization, and machine learning.",
                            Name = "Data Science",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CourseCount = 0,
                            Description = "Courses on CI/CD, containers, and infrastructure automation.",
                            Name = "DevOps",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CourseCount = 0,
                            Description = "Introduction to relational and non-relational databases.",
                            Name = "Databases",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CourseCount = 0,
                            Description = "Courses on HTML, CSS, JavaScript and modern frameworks.",
                            Name = "Frontend",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CourseCount = 0,
                            Description = "Learn backend technologies and server-side programming.",
                            Name = "Backend",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CourseCount = 0,
                            Description = "Build apps for iOS and Android platforms.",
                            Name = "Mobile Development",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CourseCount = 0,
                            Description = "Explore AWS, Azure, GCP and cloud infrastructure.",
                            Name = "Cloud Computing",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CourseCount = 0,
                            Description = "Understand security principles and ethical hacking.",
                            Name = "Cybersecurity",
                            Status = 0
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entity.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Course", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d02b327-6370-41c7-95bb-6a8d72b72848"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Created = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn the fundamentals of C#.",
                            Duration = "3 weeks",
                            LastUpdated = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 0,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Status = 1,
                            Tags = "C#,programming,fundamentals",
                            Title = "Intro to C#"
                        },
                        new
                        {
                            Id = new Guid("8d02b327-6370-41c7-95bb-6a8d72b72847"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Created = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Master object-oriented programming concepts in C#.",
                            Duration = "4 weeks",
                            LastUpdated = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 1,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Status = 1,
                            Tags = "C#,OOP,classes,inheritance",
                            Title = "OOP in C#"
                        },
                        new
                        {
                            Id = new Guid("8d02b327-6370-41c7-95bb-6a8d72b72846"),
                            CategoryId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Created = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build and deploy RESTful APIs using ASP.NET Core.",
                            Duration = "5 weeks",
                            LastUpdated = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 2,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Status = 1,
                            Tags = ".NET,ASP.NET Core,API,REST",
                            Title = "Advanced .NET APIs"
                        },
                        new
                        {
                            Id = new Guid("8d02b327-6370-41c7-95bb-6a8d72b72845"),
                            CategoryId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Created = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Understand SQL basics and database querying.",
                            Duration = "2 weeks",
                            LastUpdated = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 0,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Status = 1,
                            Tags = "SQL,database,queries,beginner",
                            Title = "SQL for Beginners"
                        },
                        new
                        {
                            Id = new Guid("8d02b327-6370-41c7-95bb-6a8d72b72844"),
                            CategoryId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Created = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Master Entity Framework Core for modern data access.",
                            Duration = "4 weeks",
                            LastUpdated = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 1,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Status = 1,
                            Tags = "EF Core,Entity Framework,data access,.NET",
                            Title = "EF Core Masterclass"
                        },
                        new
                        {
                            Id = new Guid("8d02b327-6370-41c7-95bb-6a8d72b72843"),
                            CategoryId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Created = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create beautiful static websites using HTML and CSS.",
                            Duration = "2 weeks",
                            LastUpdated = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 0,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Status = 1,
                            Tags = "HTML,CSS,web design,frontend",
                            Title = "HTML & CSS Basics"
                        },
                        new
                        {
                            Id = new Guid("8d02b327-6370-41c7-95bb-6a8d72b72842"),
                            CategoryId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Created = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn how to build reactive UIs using React.",
                            Duration = "4 weeks",
                            LastUpdated = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 1,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Status = 1,
                            Tags = "React,JavaScript,frontend,UI",
                            Title = "React Essentials"
                        },
                        new
                        {
                            Id = new Guid("8d02b327-6370-41c7-95bb-6a8d72b72841"),
                            CategoryId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Created = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Write unit tests and follow TDD in .NET.",
                            Duration = "3 weeks",
                            LastUpdated = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 1,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Status = 1,
                            Tags = ".NET,testing,TDD,unit tests",
                            Title = "Unit Testing in .NET"
                        },
                        new
                        {
                            Id = new Guid("8d02b327-6370-41c7-95bb-6a8d72b72840"),
                            CategoryId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Created = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Master version control with Git and GitHub.",
                            Duration = "1 week",
                            LastUpdated = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 0,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Status = 1,
                            Tags = "Git,GitHub,version control,beginner",
                            Title = "Git & GitHub Basics"
                        },
                        new
                        {
                            Id = new Guid("8d02b327-6370-41c7-95bb-6a8d72b72849"),
                            CategoryId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Created = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Containerize and deploy apps with Docker.",
                            Duration = "3 weeks",
                            LastUpdated = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 2,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Status = 1,
                            Tags = "Docker,containers,devops,deployment",
                            Title = "Docker for Developers"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entity.Course", b =>
                {
                    b.HasOne("ApplicationCore.Entity.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ApplicationCore.Entity.Category", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
